# Generated by Django 3.2.6 on 2021-08-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_type',
            new_name='type',
        ),
    ]
